### ISSUE TITLE
照片显示问题

### ISSUE THREAD

**Issue by zxhu-001** [wangzhengyr/koishi-plugin-msbot#1]
大佬，这个冒险岛这个插件，词条图片群里咋样才可以使用，私聊正常，群里聊不显示词条图片。官方搭建的，不是第三方接入。

**Comment by wangzhengyr** [comment]
官方搭建是指qq官方机器人么，那个还可以私聊么不清楚
目前我测试qq官方机器人词条功能都不会触发，可能需要适配
我一直都是用的onebot协议的，主要mvp功能需要主动推送，qq官方机器人目前不能满足这个需求所以没怎么测试过
有些功能都需要能访问外网，联盟查询和公告的功能都是外网

**Comment by zxhu-001** [comment]
私聊是正常的，onebot也正常。就是群里不行，现在群里就公告、联盟查询、roll、今日早报都能用。就这个词条我看日志里面
![V_55YLJ}~PCB8_VEEIGTYEU](https://github.com/user-attachments/assets/cbef1f05-9055-4958-80ca-86aed278c3f6)显示这个。正常的私聊是这样的
![W_B%_KARH36YUN63V5%M_9D](https://github.com/user-attachments/assets/b50ddce5-3f1e-486c-9d59-e439ce3c226b)
大佬什么适配一下呗。还有个问题，roll能不能设置roll 40的设置，就是在40内随机。

**Comment by zxhu-001** [comment]
大佬什么增加个懒猫的ask定时功能。

**Comment by wangzhengyr** [comment]
> 私聊是正常的，onebot也正常。就是群里不行，现在群里就公告、联盟查询、roll、今日早报都能用。就这个词条我看日志里面 ![V_55YLJ}~PCB8_VEEIGTYEU](https://private-user-images.githubusercontent.com/187188879/387551767-cbef1f05-9055-4958-80ca-86aed278c3f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDM2MzksIm5iZiI6MTczMjAwMzMzOSwicGF0aCI6Ii8xODcxODg4NzkvMzg3NTUxNzY3LWNiZWYxZjA1LTkwNTUtNDk1OC04MGNhLTg2YWVkMjc4YzNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwODAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjIxN2NlMTNhYjk1N2YzNzI4OTgyMzU3YzE3YTY4NDMyOGViNzM3MmE2MTY2ZWUxM2JmN2NkODIxZjdkNzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z8MUQPnwN9fnY_n5wGyMwR8tmMElCGSy4dpIGk1wyrg)显示这个。正常的私聊是这样的 ![W_B%_KARH36YUN63V5%M_9D](https://private-user-images.githubusercontent.com/187188879/387552132-b50ddce5-3f1e-486c-9d59-e439ce3c226b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDM2MzksIm5iZiI6MTczMjAwMzMzOSwicGF0aCI6Ii8xODcxODg4NzkvMzg3NTUyMTMyLWI1MGRkY2U1LTNmMWUtNDg2Yy05ZDU5LWU0MzljZTNjMjI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwODAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTI5Y2VmNDhlZWZmZjczMzBhYTJiNDgzY2M5ZDNkZDdlNTQzNTY5NjExODgwMTkxMmEwMjhkNzUzZDZmYTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xkKGTizMEdIFTTJwKlPFZIAEOzl6o1RQ5Wi1e5H5zHg) 大佬什么适配一下呗。还有个问题，roll能不能设置roll 40的设置，就是在40内随机。

roll可以在插件配置页面配置
![image](https://github.com/user-attachments/assets/b0a3a3f8-0cd1-4529-b8c2-039ac5545d2c)
群聊不行可能要看看你怎么用的截图了，我这里测试是可以的，公告我是配合另一个定时插件定时执行的，这样官方公告一出来就可以推送到群里
